name: Build and Release
"on":
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: |
                  npm i pnpm -g
                  pnpm i
            - name: Build
              run: |
                  pnpm run build
                  pnpm run build:zip
                  pnpm run build:chrome
                  pnpm run build:zipChrome
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  tag_name: ext-release-${{ github.run_number }}
                  release_name: Extension Release
                  body: |
                      # Firefox store

                      [Chess.com cheats](https://addons.mozilla.org/en-US/firefox/addon/chess-com-cheats/) is available on the firefox store, though it takes time to get approved, so using the extension from here is recommended.

                      # Manual installation

                      ## Firefox

                      1. Download the zip file below (`chess-cheats.zip`)
                      2. Go to `about:debugging#/runtime/this-firefox` in firefox
                      3. Click on "Load Temporary Add-on"
                      4. Select the downloaded zip file

                      ## Chrome

                      1. Download the zip file below (`chess-cheats.zip`)
                      2. Go to `chrome://extensions` in chrome
                      3. Enable developer mode
                      4. Click on "Load unpacked"
                      5. Select the downloaded zip file

                      ### Note

                      `chess-cheats-v3.zip` is a manifest v3 version of the extension. It is just used for the chrome web store and v2 is preferred.
                  draft: false
                  prerelease: false
            - name: Upload Release Asset
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./chess-cheats.zip
                  asset_name: chess-cheats.zip
                  asset_content_type: application/zip
            - name: Upload Release Asset v3
              id: upload-release-asset-v3
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./chess-cheats-v3.zip
                  asset_name: chess-cheats-v3.zip
                  asset_content_type: application/zip
