name: Build and Release
"on":
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install dependencies
              run: |
                  npm i pnpm -g
                  pnpm i
            - name: Build
              run: |
                  pnpm run build
                  pnpm run build:zip
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  tag_name: ext-release-${{ github.run_number }}
                  release_name: Extension Release
                  body: |
                      # Installation

                      1. Download the zip file
                      2. Extract the zip file
                      Follow the instructions for your browser:

                      ## Chrome

                      3. Go to [chrome://extensions](chrome://extensions)
                      4. Enable developer mode
                      5. Click on "Load unpacked"
                      6. Select the extracted folder
                      7. Done! (You have to redo 3-6 every time you restart chrome)

                      ## Firefox

                      3. Go to [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
                      4. Click on "Load Temporary Add-on"
                      5. Select any file in the extracted folder
                      6. Done! (You have to redo 3-5 every time you restart firefox)

                      ## Edge

                      3. Go to [edge://extensions](edge://extensions)
                      4. Enable developer mode
                      5. Click on "Load unpacked"
                      6. Select the extracted folder
                      7. Done! (You have to redo 3-6 every time you restart edge)
                  draft: false
                  prerelease: false
            - name: Upload Release Asset
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist/rel.zip
                  asset_name: rel.zip
                  asset_content_type: application/zip
